apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:1vq+OtJDgDA/1B2gXM5/tlhAv4+FQ2y8tqKu6BS4oUMm+Y0eXYIjlxd+BRNJoacgIQE7mbz1uuPvjSfhrGluc9hcPdtmoXNcke/7nkGFWDrvwRgXYOiU4ZYoP1vmvn6gvHL8uS2KYb8vDz7IgE9zjq7kGZviQgBRMbMNHXq3VV8zJSJUmeM6jMhOp/g2HOoFhFP5M+xXI4A7D1WlSBEe/cRqgXFvvdJXGGPtuNxdFTGAdbggxSoc2i2n50/l2+AmSbix3Ng3vzzBCreLVFPmMZuhAukpyEV8WD5YeT7k1VijNzJPLOoO4knOFpk=,iv:Yh4A/znlkbSIzwC58lJXh78IkZCQZXk46A5mP+umBoA=,tag:8MXAjpj6BUkJZP1GLVruKg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age16extgxwyqtx2v9te9cslde4a5x2c6z6dtnl8ru4w32678yynvphsvmguzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SHZDbHEwTWhBdUlPUURG
            NzlXY2tPOWJzYWxmTDY5TVhQUHl3UWhpTFFRCnhXTGdRcUpHZXVUQi8zUnpxUHpZ
            eEE1K1N5THhxL3dMb3c0QllaWUZwQUEKLS0tIDU0WVIwM1orRnlsWmlFeUFnV0pm
            KzBqQzZWQVM1TnNTYXRKeVRPRERpTFkKThagCWHPd03/3PqNQhBEhoSeut+PRL7L
            msoq38d/SOvbLHom40DH+j6UwtYGBMNJcJ7ElrjtnM1ENKeZaPf2vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T04:03:04Z"
    mac: ENC[AES256_GCM,data:+1Hts4c3guXMhC1fBp67REKYtJl30Wkwg+kNRP/pVJo/tvJIoUJaXOCG3zKqrEH5CC7TkbPiJT3K7QXR8jZqsSGopCoGf25TpBdyDrjnGrkjjqCpzhhDTKqp2aAUJMVl6x/ne3PpAwiJnnE/ue5/3egm7cmE3trznFbzNqCTpNY=,iv:eboQMHU4B0jlwwvvLJdHzvC2NCtWA5/be7psVOwvfss=,tag:G8bm/YwoBkLavi8yZdPieQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
