apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:65KX/S2r4+I=,iv:Ho3Eg6Wsp8GS6+RIfukSUrKjf+gZAIjywYanfNmkEJM=,tag:fiVFAp9WbuBLakGhVzpN3w==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:4XFKYLf8/WAL4+7+Pcc6NQ==,iv:u82KPIzpS8AmcNCLqIqB15QMC5MAuoQ2rI+w4okgfOk=,tag:mkIHEagRQ/AJbnWNYAaYsQ==,type:str]
kind: Secret
metadata:
    name: linkding-secret
sops:
    age:
        - recipient: age16extgxwyqtx2v9te9cslde4a5x2c6z6dtnl8ru4w32678yynvphsvmguzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWk9MRER6cnVTRXhJYXlZ
            U1BoL01DQ0pCbTg1eDlFZVNDUFNnbUt6MXlVCjMySko3ZDFLT0oxcWhsMDRRbXpz
            V1BzdEJwbUp3ekZaL1BlbFNueldxb0kKLS0tIHo0c3JkSEpkTUN4dENyMHF3ZGFw
            QnI1dm5EWkp6RGxLQWlUTUxSZVJESXcKLP4hP5oXl+Vreh8F4v0zNHWudiYvaode
            EvQ+IDs5XmuWq3YRrLrzTF4lyDE/LtmIIuw/jJDl3qgMezhGfh7hWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T04:18:26Z"
    mac: ENC[AES256_GCM,data:yN1qLS+N9+feff99pIhqyQ5V1HJBBm+GZsWAf1C6sFgAuUaT/AHchiGbSEke9vAPQK0m4aGJAiXlKRf094rmjD9AZT0SzXScnr1bIevCCxxYBi+ILEI+ZQkjwfNQV98gYD+x+WyEr1/iX6Y4NMWK810r5jpEbQPKTWL0P/smZBM=,iv:pFXimyN0GN74jXkGHHbX+JO6UcdPVoBIM1OF/FQQ4k4=,tag:iKP1+8RefoSdejh+xS2h+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
