apiVersion: v1
data:
    password: ENC[AES256_GCM,data:UEBKj+iKRyk=,iv:8ao9PEqWRIC5uqmq1p2Dcy9PY0srkTF6D2IQovLHAzo=,tag:7ha5nITTQ0VK0KcJ4NsMFA==,type:str]
    user: ENC[AES256_GCM,data:YAbDb979jHw=,iv:bkXFdYNp/OsAGR4nKSCQ2uhuKdrxhAT4qMUxbOA4lvY=,tag:kUoVqRpJLi9ppJilD656hw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age16extgxwyqtx2v9te9cslde4a5x2c6z6dtnl8ru4w32678yynvphsvmguzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTW1PSUw1M3BzTURvUU54
            QytQYjVPN1loTU9URWcyK3A5Y3JPSm05YWtzCjduTnpuVGFBSnh1Y0hqRjA0RjFQ
            WVBFdkduNk5TdTBrZUVZU0lkZFA0YkEKLS0tIGNoWmF3NENVT3VGRjRoTlkzWU1K
            dVNjNlVYMXVjNEhkQVNqSUozalFYQTQKigJ52vAmPXe08SUbHGCorURPCOnuWBJA
            dL8D/HCpkeMul0BdDyNZsyIgUPZK6rWHkWsouVGc7Yjg5n+yAcp1Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T03:23:25Z"
    mac: ENC[AES256_GCM,data:SxekB+YgqPPQHB1Unbb4O+1Fj8Nn5pRuQjo2TM0igsb4zmIYjbGWCrt5FR9+esmFzSOVxam0BPfxwEaES0HqkYrP2LhUpREfO3qVu522ilSr3l0+GUG3Ef6LynhiDrcdkliA4dx+Em3VVB1wVaKFy61WCRTBRuXlYTUlkyqV2PI=,iv:ZF1CzqWc0T2SVpjbdDwZM8Ym8zlATl2x//ifMWlu7EY=,tag:jQVJC5wCIwavu1DHDiQH9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
