apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:KT+tQowfV7L+u9rcxGxeqmFaXRBkifHhVdtUbymBuW75zsIzeN7rJp87rajDN+mg2yY20FDhW1U=,iv:47UjD2KXcQFKRlNsmA0gJjk4Hzn3jaZ8Ql0TRIYgP2M=,tag:WZiN2fMN17WTjOEOj+ujlw==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age16extgxwyqtx2v9te9cslde4a5x2c6z6dtnl8ru4w32678yynvphsvmguzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVVdaQUh2b083eVV6RFBN
            M25JeFpiQjRmcTZPdFo5elRvWDBuSG1ZY3pnCmd0Qlc4SjhlOGVKSlV1NzRuYWhk
            WXF4eVRkVnZHYW5wNHNtU1o2QTcvYjgKLS0tIGhldzA2YWxyWWJLekhqWmdBTWwz
            QTFLV3JKa2tIeENLU3BuSkVGdXNNNm8KDLiVWHx1HeeOaDEaQG99Nb0NixbQGS/K
            WfP2sBJ3NEaQDEOZz6MUdTV1IjQD27AJc27pTzPRgOaY18oTUKmsKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T11:04:29Z"
    mac: ENC[AES256_GCM,data:IHrqkgkDDrU/AZETHCTObaVvthCb4mYHLFisv46GraSwwEKl1XuiE7TddZ1e/RKgMK0g6lvwKiQq/6mTrWV4cY5WO6gTz+o/ishMS+J4NF68Y74LIeEVm1DqFzVSTlkllWZ65tDiHbJY2wRtZE/QXEG97+cPgxsHiIJSVxIRxb4=,iv:jT8ist5wKDACqhx+sfj+TfhX4smhlthhG7UnDfKzPog=,tag:DZgaf4s4MCETM60sS8XPIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
